### ISSUE TITLE
Perhaps put vector tools on the right of the editor?

### ISSUE THREAD

**Issue by infinitytec** [infinitytec/I-Cant-Believe-Its-Not-2#11]
![image](https://user-images.githubusercontent.com/13670462/50945079-b225a580-1458-11e9-9b5f-4d22eaf1be51.png)

**Comment by gliczide** [comment]
Actually, you can.

`.paint-editor_top-align-row_25164 {
    direction: rtl !important;
}
.paint-editor_mode-selector_28iiQ {
    display: grid;
}`

**Comment by infinitytec** [comment]
I'll try that out. Thanks.

**Comment by infinitytec** [comment]
OK, that looks reasonable enough to me. Bitmap tools are also on the left with this but to be honest it kind of makes more sense that way.

**Comment by infinitytec** [comment]
Added in 1.8.4

**Comment by gliczide** [comment]
Textarea bug fixed:
`textarea.paint-editor_text-area_27Ci4, .paint-editor_canvas-container_x2D0a {
    direction: ltr;
}`
