### ISSUE TITLE
the player and fullscreen looks weird

### ISSUE THREAD

**Issue by scratchly-a** [infinitytec/I-Cant-Believe-Its-Not-2#15]
the title explains it all.
![Screenshot 2021-02-12 at 20 00 06](https://user-images.githubusercontent.com/74501935/107810507-153b4200-6d6d-11eb-8cf5-357f5ce13ceb.png)
![Screenshot 2021-02-12 at 20 00 11](https://user-images.githubusercontent.com/74501935/107810519-19675f80-6d6d-11eb-865c-ed655070a1b9.png)

**Comment by infinitytec** [comment]
I will look into this.

**Comment by gliczide** [comment]
this is gonna fun while waiting.

**Comment by gliczide** [comment]
also same problem having 1600x900 resolution

**Comment by infinitytec** [comment]
OK updating the userscript to 1.8.3 should resolve these issues.
